version: '3.8'
services:
  laravel-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=projects
      - DB_USERNAME=root
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=projects
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
